### ISSUE TITLE
AcademyCraft does not see LambdaLib

### ISSUE THREAD

**Issue by handicraftsman** [LambdaInnovation/LambdaLib#3]
AcademyCraft requires LIUtils, but i can't download this library. Also, mojang servers disallows me to download AnnotationRegistry (needed to compile)

**Comment by WeAthFoLD** [comment]
[AnnoReg 2.0r1](http://www.li-dev.cn/data/mod/AnnotationRegistry-2.0r1.jar)
[LIUtils 1.0r1](http://www.li-dev.cn/data/mod/LIUtils-1.0r1.jar)

**Comment by handicraftsman** [comment]
Does not helps xD Just included files at 1.7.10-blablabla.jar

**Comment by WeAthFoLD** [comment]
What do you mean by including files? Those mods are standard forge mods and you should place them in .minecraft/mods, making sure the forge is properly installed.

**Comment by handicraftsman** [comment]
No. ACraft requires plugins not mods xD

**Comment by WeAthFoLD** [comment]
AcademyCraft is also a forge mod.

**Comment by handicraftsman** [comment]
I know. Forge also have plugins - builtin into minecraft.jar mods.

**Comment by handicraftsman** [comment]
Also, you forbid "Redistribute the project in source-code or binary form". But it's against GPL.

**Comment by handicraftsman** [comment]
Orr.. wait xD Poor english

**Comment by WeAthFoLD** [comment]
Coremod can now also be put in mods folder without installing them into jar :I

**Comment by handicraftsman** [comment]
Not helps, weatherfold)

**Comment by WeAthFoLD** [comment]
I'm just saying that it's standard way of installation for AC. Works for me and everyone else. If it does not work, there might be some problem on your side. Forge version and other mods intalled please?

**Comment by handicraftsman** [comment]
idk, because it updates automatically. And no mods installed.

**Comment by handicraftsman** [comment]
But mod is cool. 
P. S. I hate running "~/java8/jre1.8.0_60/bin/java -jar launcher.jar" to start game

**Comment by WeAthFoLD** [comment]
You can find out by logs in your `.minecraft/logs` folder。

**Comment by handicraftsman** [comment]
I knowww.... I am speaking with minecraft modder (sometimes)

**Comment by handicraftsman** [comment]
Also i am C/C++ coder

**Comment by WeAthFoLD** [comment]
As mentioned earlier, as long as you put AC, AR LIU into mods folder and you use JRE8 for game startup with Forge 1448+ installed, everything works well. If that doesn't work, you should probably state your problem more clearly... Like providing the startup log.

**Comment by handicraftsman** [comment]
My. game. is. not. crashes!!!

**Comment by WeAthFoLD** [comment]
There ARE startup logs even if game does not crash. `fml-client-0.log`

**Comment by handicraftsman** [comment]
BUT: all mods are working now

**Comment by WeAthFoLD** [comment]
Alright, I think we have some misunderstanding. You are saying that dependencies are not automatically downloaded?

**Comment by handicraftsman** [comment]
Nope

**Comment by WeAthFoLD** [comment]
Please state your problem more clearly then. I don't even know what exactly you are encountering.

**Comment by handicraftsman** [comment]
I don't have problem, because i found how to fix it. This topic - just message, because players must can easily install mod.

**Comment by WeAthFoLD** [comment]
~~OK. Currently dependencies are mentioned in the download pages and players have to manually download the jars. In the future we might implement some mechanism to automatically download libraries or warn players when they do not have the correct library installed. Thanks for pointing this out.~~

**Comment by handicraftsman** [comment]
xD

**Comment by WeAthFoLD** [comment]
If you are trying to BUILD the project you should point out at the very beginning. Your statement at the beginning is very confusing, and I thought you are playing around with release versions.

Gradle build is now correctly set up in `dev` branches for `LambdaLib` and `AcademyCraft`.

**Comment by gakongren** [comment]
Ooop..I was confused by this issue...I would only say sth I know.
LIUtil and AnnoReg are minecraft mods and for installing, we don't need to do more than just put them in the "mods" folder..
LambdaLib is another thing that I remember is not being used in AC mod now...As @WeAthFoLD said that it will be used.for next pr for AC mod...
Still, I think maybe is better to state the problem clearly at first...Idk what the thing you are really want to point out...
