### ISSUE TITLE
gradlew构建失败

### ISSUE THREAD

**Issue by Paindar** [LambdaInnovation/LambdaLib#31]
- What went wrong:
  Could not resolve all dependencies for configuration ':compile'.
  > Could not resolve cn.lambdalib:LambdaLib:1.2.0.
  Required by:
      com.yourname.modid:MCMODMaker:1.0
  > Could not GET 'https://libraries.minecraft.net/cn/lambdalib/LambdaLib/1.2.0
  /LambdaLib-1.2.0.pom'. Received status code 403 from server: Forbidden

我已将LambdaLib-PluginLoader.jar放到了根目录/eclipse/mods文件夹下，然而似乎并没有起到什么帮助，请问可以为我提供一些帮助吗
*I have put LambdaLib-PluginLoader.jar into the  /eclipse/mods  folder. However it seems to make no difference. Could you please support me any help?

是的我的英语水平很烂。
*Thanks.

**Comment by WeAthFoLD** [comment]
LambdaLib现在并没有publish到maven等工件仓库，因此在项目里引用LambdaLib时需要先在本地clone，然后从源代码构建LambdaLib（`gradlew install`）。

在项目中引用的时候需要在`repositories`里引入`mavenLocal()`，详细的build.gradle配置在README中已有描述。

**Comment by Paindar** [comment]
事实上上述错误提示是发生在gradlew install期间的-。-

我先构建了MDK（或是MCP？我是1.7.10）
然后将lambdaLib的文件拷入MCP文件夹（并没有全部拷贝，如build.gradle和build.properties )
按照readme.me修改了build.gradle
然后我将LambdaLib-PluginLoader.jar拷贝到了根目录/eclipse/mods下（根目录是指MCP文件夹）
然后进行geadlew install 得到上述错误提示

不是很明白哪里出了问题（我甚至还没打开eclipse 在整个过程中）
望不吝赐教。

**Comment by WeAthFoLD** [comment]
1. “从源代码构建LambdaLib”的意思是把LambdaLib clone下来，然后直接在LambdaLib的repo目录运行`gradlew install`. 这样做的目的是把LambdaLib自己的jar构建出来并且上传到maven的local repository（也即`mavenLocal()`）。在使用自己的项目时，只需要修改build.gradle，指明对该jar的引用即可，无须拷贝或者复制任何文件。
2. 注意README中的原文:
   
   > Note that when you include source code, you must put jars\LambdaLib-PluginLoader.jar into the eclipse\mods folder.
   
   只有在你需要把LambdaLib的**源代码**链入工作空间的时候，才需要这个PluginLoader。如果你是引用jar进行开发，并不需要复制PluginLoader。

综上，如果要引用LambdaLib的jar进行开发，正确的设置流程如下：
- clone LambdaLib
- 在LambdaLib的根目录运行`gradlew install`
- 在你的项目目录按照README配置`build.gradle`
- DONE，可以在你的项目目录使用`gradlew build`测试一下

(好像感觉README写的有点误导人？之后会酌情修改一下的

**Comment by Paindar** [comment]
看起来可以了（#挠头）

感谢帮助

再有状况会来接着麻烦的（并不XD）

**Comment by WeAthFoLD** [comment]
~
